### PR TITLE
Catches messages that are NEarlY all caps now

### PR DESCRIPTION
**Pull request by skittlemittle**

### CODE REVIEW

**Review by ClobberXD — CHANGES_REQUESTED** [review]
Even messages with just two upper-case letters trigger warnings; nearly all-caps means _almost_ all the letters are in upper-case. There'd be too many false positives.

I appreciate your initiative to improve this mod here is some food for thought:
- You could return true only if `capscounter` > n% of `message:len()`
  - e.g. if `message:len() == 10`, the warning should be triggered only when `capscounter > 7`

**Comment by skittlemittle** [comment]
This is a pretty crude implementation

>Even messages with just two upper-case letters triggers a warning

We can add pattern detection to detect when people Title Case or whatever

**Comment by ClobberXD** [comment]
You are welcome to improve this mod in any way you deem fit. You just need to make sure that it works alright. :)

**Comment by skittlemittle** [comment]
I initially wanted to make it only flag the message if a certain percentage of the message is caps, just as you said. 

I'll reimplement it as soon as possible.
What percentage would you like? 30% perhaps

**Comment by ClobberXD** [comment]
30% seems to be too less...

Let's take an example: This sentence, "OMG you're so OP", would trigger a warning, just because the player capitalized the abbreviations.

I'd say a percentage of 70 would be ideal. If a chat message consists of upper-case letter more than 70-75%, it's most likely that the player is intentionally using CAPS, as opposed to the example above.

**Comment by skittlemittle** [comment]
Ok, I also think it should have a command to adjust the sensitivity percentage

**Comment by ClobberXD** [comment]
I think a minetest.conf value would be a more elegant solution, without which you'd have to implement mod storage just to store one value...

The key could be called `caps_alert.<whatever_you_wish>`

**Comment by skittlemittle** [comment]
It now checks the amount of CAPITAL letters in the messages, and if they exceed the `sensitivity` setting it returns true.

The sensitivity setting is a `minetest.conf` setting and I made it default to 50 percent as in some LAN testing with a few other people we found 70 percent was too lenient.

70% is too lenient because of the way the filter works, as it converts spaces numbers and other characters that are not letters into a lower case 'a' (this is done as `char:upper()` thinks that spaces, numbers and stuff are CAPITAL letters) these show up as lower case letters and so affect the ratio of UPPER to lower case letters, making the filter more aggressive fixes this.

**Review by ClobberXD — APPROVED** [review]

**Comment by ClobberXD** [comment]
Good work!

Looks like the original code had a major bug already... >.<

**Pull request merged**
